# Generated by Django 4.2.4 on 2023-10-12 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0009_placement_achievement"),
    ]

    operations = [
        migrations.CreateModel(
            name="workshop_Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollno", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(max_length=255)),
                ("title1", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("fromdate", models.DateField()),
                ("todate", models.DateField()),
                ("days", models.CharField(max_length=10)),
                (
                    "photo1",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievement_photos/"
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievement_photos/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
