# Generated by Django 4.2.4 on 2023-10-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_workshop_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracurricular_achievement",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
